markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Od-Erdene
tagline:          'I like KISS. By KISS I means "keep it simple and stupid". '
baseurl:          /

author:
  name:           Odkoo

paginate:         5
recent-num:       5
article_num:      5
